import datetime
import logging
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

from agents.capability_agent import CapabilityAgent
from agents.critic_agent import CriticAgent
from agents.market_agent import MarketAgent
from agents.research_agent import ResearchAgent
from agents.strategy_agent import StrategyAgent

from core.cache import SimpleCache
from core.memory import AgentMemory
from llm.groq_client import GroqClient

logger = logging.getLogger(__name__)


class Orchestrator:

    def __init__(self, api_key: str):
        import os
        os.environ["GROQ_API_KEY"] = api_key

        self.llm = GroqClient()
        self.cache = SimpleCache()
        self.memory = AgentMemory()

        self.research = ResearchAgent(self.llm, self.cache, self.memory)
        self.market = MarketAgent(self.llm, self.cache, self.memory)
        self.capability = CapabilityAgent(self.llm, self.cache, self.memory)
        self.strategy = StrategyAgent(self.llm, self.cache, self.memory)
        self.critic = CriticAgent(self.llm, self.cache, self.memory)
        self.visualization = VisualizationAgent(self.llm, self.cache, self.memory)
        self.tldr = TLDRAgent(self.llm, self.cache, self.memory)

    def run(self, market: str, progress_callback=None) -> dict:
        logger.info("Starting MNI pipeline for market: %s", market)
        start_time = time.time()
        analysis_start = datetime.datetime.utcnow()

        def update_progress(stage: str, message: str):
            if progress_callback:
                progress_callback(stage, message)
            logger.info("[%s] %s", stage, message)

        update_progress("Research", "Fetching live data from all sources...")
        self.research.run(market)
        update_progress("Research", "✓ Data collection complete")

        update_progress("Analysis", "Running market and capability analysis in parallel...")

        with ThreadPoolExecutor(max_workers=2) as executor:
            futures = {
                executor.submit(self.market.run, market): "Market",
                executor.submit(self.capability.run, market): "Capability",
            }
            for future in as_completed(futures):
                agent_name = futures[future]
                try:
                    future.result()
                    update_progress("Analysis", f"✓ {agent_name} analysis complete")
                except Exception as exc:
                    logger.error("%s agent failed: %s", agent_name, exc)
                    raise

        update_progress("Strategy", "Synthesizing strategic entry plan...")
        self.strategy.run(market)
        update_progress("Strategy", "✓ Strategy synthesis complete")

        update_progress("Review", "Running quality review...")
        critic_feedback = self.critic.run(market)
        sections_to_rerun = critic_feedback.get("sections_to_rerun", [])
        update_progress("Review", "✓ Quality review complete")

        refinement_count = 0

        if sections_to_rerun:
            update_progress("Refinement", f"Refining {len(sections_to_rerun)} section(s)...")

        if "market_analysis" in sections_to_rerun:
            instructions = (
                critic_feedback.get("sections", {})
                .get("market_analysis", {})
                .get("improvement_instructions", "")
            )
            if instructions:
                self.market.refine(market, instructions)
                refinement_count += 1
                print("[Orchestrator] Refined: market_analysis")

        if "capabilities" in sections_to_rerun:
            instructions = (
                critic_feedback.get("sections", {})
                .get("capabilities", {})
                .get("improvement_instructions", "")
            )
            if instructions:
                self.capability.refine(market, instructions)
                refinement_count += 1
                print("[Orchestrator] Refined: capabilities")

        if "strategy" in sections_to_rerun:
            instructions = (
                critic_feedback.get("sections", {})
                .get("strategy", {})
                .get("improvement_instructions", "")
            )
            if instructions:
                self.strategy.refine(market, instructions)
                refinement_count += 1
                print("[Orchestrator] Refined: strategy")

        if refinement_count:
            update_progress("Refinement", f"✓ {refinement_count} section(s) refined")

        final_market = self.memory.get("market_analysis") or ""
        final_capabilities = self.memory.get("capabilities") or ""
        final_strategy = self.memory.get("strategy") or ""
        final_research = self.memory.get("research") or {}

        final_report = f"""# Market Intelligence Report — {market}

## 1. Market Analysis

{final_market}

## 2. Capability Analysis

{final_capabilities}

## 3. Strategic Entry Plan

{final_strategy}

---

*Report generated by Market Narrative Intelligence (MNI).
Data sourced in real-time from DuckDuckGo, Wikipedia,
and HackerNews. Self-refined using AI quality control.*
"""
        self.memory.set("final_report", final_report)
